# image: node:latest
image: microsoft/azure-cli:latest

stages:
  - build
  - deploy

variables:
  AZURE_WEBAPP_NAME: naturecounter
  AZURE_RESOURCE_GROUP: nature_counter
  AZURE_APP_SERVICE_PLAN: nature-app
  AZURE_WEBAPP_PACKAGE_PATH:

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src $AZURE_WEBAPP_PACKAGE_PATH --slot $AZURE_WEBAPP_SLOT_NAME --output tsv

  only:
    - manual